<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>ConnectMe.Core</RootNamespace>
    <Version>1.6.9</Version>
    <AssemblyVersion>1.6.9</AssemblyVersion>
    <FileVersion>1.6.9</FileVersion>
  </PropertyGroup>

</Project>
