<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>ConnectMe.Windows</RootNamespace>
    <AssemblyName>ConnectMe.Windows</AssemblyName>
    <Version>1.7.2</Version>
    <AssemblyVersion>1.7.2</AssemblyVersion>
    <FileVersion>1.7.2</FileVersion>
    <InformationalVersion>1.7.2 (v1-7-2)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConnectMe.Core\ConnectMe.Core.csproj" />
  </ItemGroup>

</Project>
